# These are supported funding model platforms

github: way2pramil
# ko_fi: # Replace with your Ko-fi username if you have one
# patreon: # Replace with your Patreon username if you have one
# buy_me_a_coffee: # Replace with your BMC username if you have one
