"""
KiNotes PDF Exporter - Export notes as PDF
"""
import os
from datetime import datetime

try:
    import wx
    HAS_WX = True
except ImportError:
    HAS_WX = False

try:
    import pcbnew
    HAS_PCBNEW = True
except ImportError:
    HAS_PCBNEW = False


class PDFExporter:
    """Export notes to PDF format."""
    
    def __init__(self, project_dir):
        """Initialize with project directory."""
        self.project_dir = project_dir
    
    def _get_project_name(self):
        """Get project name from directory or board."""
        if HAS_PCBNEW:
            try:
                board = pcbnew.GetBoard()
                if board:
                    filename = board.GetFileName()
                    if filename:
                        return os.path.splitext(os.path.basename(filename))[0]
            except:
                pass
        
        return os.path.basename(self.project_dir)
    
    def _get_default_filename(self):
        """Generate default PDF filename."""
        project_name = self._get_project_name()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        return f"{project_name}_notes_{timestamp}.pdf"
    
    def export(self, content, filepath=None):
        """
        Export notes content to PDF.
        
        Args:
            content: Markdown text content
            filepath: Optional output path. If None, prompts user.
        
        Returns:
            Path to exported file, or None if cancelled/failed
        """
        if not HAS_WX:
            raise RuntimeError("wxPython required for PDF export")
        
        # Get output path
        if not filepath:
            filepath = self._prompt_save_location()
            if not filepath:
                return None
        
        try:
            # Use wx.html2 for rendering or simple text-based PDF
            # Since we want no external dependencies, we'll use wx printing
            return self._export_with_wx_printing(content, filepath)
        except Exception as e:
            raise RuntimeError(f"PDF export failed: {e}")
    
    def _prompt_save_location(self):
        """Show save dialog and return chosen path."""
        default_name = self._get_default_filename()
        default_dir = self.project_dir
        
        with wx.FileDialog(
            None,
            "Export Notes as PDF",
            defaultDir=default_dir,
            defaultFile=default_name,
            wildcard="PDF files (*.pdf)|*.pdf",
            style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT
        ) as dialog:
            if dialog.ShowModal() == wx.ID_OK:
                return dialog.GetPath()
        return None
    
    def _export_with_wx_printing(self, content, filepath):
        """Export using wx printing framework."""
        try:
            # Create a printout
            printout = NotesPrintout(content, self._get_project_name())
            
            # Create printer DC for PDF
            print_data = wx.PrintData()
            print_data.SetFilename(filepath)
            print_data.SetPrintMode(wx.PRINT_MODE_FILE)
            
            # Set to PDF printer if available
            # Note: This creates a print file, not a true PDF on all platforms
            # For true PDF, would need reportlab or similar
            
            dc = wx.PrinterDC(print_data)
            
            if dc.IsOk():
                printout.SetDC(dc)
                printout.OnPrintPage(1)
                return filepath
            else:
                # Fallback: Save as formatted text file with .pdf extension
                # User can convert or we notify them
                return self._export_as_text_pdf(content, filepath)
                
        except Exception as e:
            # Fallback to text export
            return self._export_as_text_pdf(content, filepath)
    
    def _export_as_text_pdf(self, content, filepath):
        """
        Fallback: Export as nicely formatted text.
        Note: This creates a text file. For true PDF, recommend installing reportlab.
        """
        # Change extension to .txt and notify
        txt_path = filepath.replace('.pdf', '.txt')
        
        project_name = self._get_project_name()
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        
        header = f"""{'='*60}
{project_name} - Design Notes
Exported: {timestamp}
{'='*60}

"""
        footer = f"""

{'='*60}
Generated by KiNotes - PCBtools.xyz
{'='*60}
"""
        
        formatted_content = header + content + footer
        
        with open(txt_path, 'w', encoding='utf-8') as f:
            f.write(formatted_content)
        
        # Also try to create actual PDF if possible
        actual_pdf = self._try_create_pdf(content, filepath, project_name)
        if actual_pdf:
            return actual_pdf
        
        # Show message about text export
        if HAS_WX:
            wx.MessageBox(
                f"PDF export created text file:\n{txt_path}\n\n"
                "For true PDF export, install 'reportlab' package.",
                "Export Note",
                wx.OK | wx.ICON_INFORMATION
            )
        
        return txt_path
    
    def _try_create_pdf(self, content, filepath, project_name):
        """Try to create actual PDF using reportlab if available."""
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
            from reportlab.lib.enums import TA_LEFT
            
            doc = SimpleDocTemplate(filepath, pagesize=A4)
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=16,
                spaceAfter=12
            )
            
            body_style = ParagraphStyle(
                'CustomBody',
                parent=styles['Normal'],
                fontSize=10,
                spaceAfter=6,
                fontName='Courier'
            )
            
            story = []
            
            # Title
            story.append(Paragraph(f"{project_name} - Design Notes", title_style))
            story.append(Spacer(1, 0.25*inch))
            
            # Content (simple line-by-line)
            for line in content.split('\n'):
                if line.startswith('# '):
                    story.append(Paragraph(line[2:], styles['Heading1']))
                elif line.startswith('## '):
                    story.append(Paragraph(line[3:], styles['Heading2']))
                elif line.startswith('### '):
                    story.append(Paragraph(line[4:], styles['Heading3']))
                elif line.strip():
                    # Escape HTML entities
                    safe_line = line.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                    story.append(Paragraph(safe_line, body_style))
                else:
                    story.append(Spacer(1, 0.1*inch))
            
            # Footer
            story.append(Spacer(1, 0.5*inch))
            footer_style = ParagraphStyle(
                'Footer',
                parent=styles['Normal'],
                fontSize=8,
                textColor='gray'
            )
            timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
            story.append(Paragraph(f"Generated by KiNotes - PCBtools.xyz | {timestamp}", footer_style))
            
            doc.build(story)
            return filepath
            
        except ImportError:
            return None
        except Exception as e:
            print(f"KiNotes: reportlab PDF failed: {e}")
            return None


class NotesPrintout(wx.Printout):
    """wx.Printout for notes content."""
    
    def __init__(self, content, title="KiNotes"):
        super().__init__(title)
        self.content = content
        self.title = title
    
    def OnPrintPage(self, page):
        dc = self.GetDC()
        if not dc:
            return False
        
        # Get page size
        w, h = dc.GetSize()
        
        # Margins
        margin = 50
        
        # Draw title
        dc.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD))
        dc.DrawText(self.title, margin, margin)
        
        # Draw content
        dc.SetFont(wx.Font(10, wx.FONTFAMILY_TELETYPE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL))
        
        y = margin + 30
        line_height = 14
        
        for line in self.content.split('\n'):
            if y > h - margin:
                break
            dc.DrawText(line, margin, y)
            y += line_height
        
        # Draw footer
        dc.SetFont(wx.Font(8, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL))
        dc.DrawText("Generated by KiNotes - PCBtools.xyz", margin, h - margin)
        
        return True
    
    def GetPageInfo(self):
        return (1, 1, 1, 1)
    
    def HasPage(self, page):
        return page == 1
